create table if not exists EVENT_E_HANDOVER(
    
    EVENT_ID TINYINT,
    START_RNC TINYINT,
    END_RNC TINYINT,
    START_C_ID INT,
    END_C_ID INT,
    IMSI BIGINT,
    DATETIME_ID TIMESTAMP     
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;