create table if not exists EVENT_E_CALLFAILURE(
    
    EVENT_ID TINYINT,
    CAUSE_VALUE TINYINT,
    EXTENDED_CAUSE_VALUE TINYINT,    
    IMSI BIGINT,
    DATETIME_ID TIMESTAMP     
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;